dist: bionic
sudo: true
language: java
jdk:
  - oraclejdk11

notifications:
  email:
    recipients:
    - jeff.yemin@mongodb.com
    - ross.lawley@mongodb.com
    - john.stewart@mongodb.com
    on_success: change
    on_failure: always

branches:
  only:
  - master

env:
  global:
    - MONGODB_FILE_NAME=mongodb-linux-x86_64-enterprise-ubuntu1804
    - MONGODB=4.2.6

addons:
  apt:
    packages:
    - libsnmp-dev

install:
  - wget http://downloads.mongodb.com/linux/${MONGODB_FILE_NAME}-${MONGODB}.tgz
  - tar xzf ${MONGODB_FILE_NAME}-${MONGODB}.tgz
  - ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/bin/mongod --version

before_script:
  - mkdir ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/data
  - ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/bin/mongod --dbpath ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/data --logpath ${PWD}/${MONGODB_FILE_NAME}-${MONGODB}/mongodb.log --setParameter enableTestCommands=1 --fork --nojournal

script:
  - ./gradlew -q assemble
  - ./gradlew check -Ptravistest=true
  - ./gradlew docs

after_script:
  - pkill mongod
