---
differenceTypes: []

packages:
- io.netty.bootstrap
- io.netty.buffer
- io.netty.channel
- io.netty.channel.embedded
- io.netty.channel.group
- io.netty.channel.local
- io.netty.channel.nio
- io.netty.channel.oio
- io.netty.channel.socket
- io.netty.channel.socket.nio
- io.netty.channel.socket.oio
- io.netty.handler
- io.netty.handler.codec
- io.netty.handler.codec.base64
- io.netty.handler.codec.bytes
- io.netty.handler.codec.compression
- io.netty.handler.codec.marshalling
- io.netty.handler.codec.protobuf
- io.netty.handler.codec.serialization
- io.netty.handler.codec.string
- io.netty.handler.logging
- io.netty.handler.ssl
- io.netty.handler.ssl.util
- io.netty.handler.stream
- io.netty.handler.timeout
- io.netty.handler.traffic
- io.netty.util
- io.netty.util.collection
- io.netty.util.concurrent
- io.netty.util.internal
- io.netty.util.internal.chmv8
- io.netty.util.internal.logging
- org.slf4j
- org.slf4j.helpers
- org.slf4j.spi
