baseurl = "/mongo-java-driver/"
languageCode = "en-us"
title = "MongoDB Java Drivers"
canonifyurls = false
disableHugoGeneratorInject = true
disableKinds = ["section", "taxonomy", "taxonomyTerm", "404"]

githubRepo = "mongo-java-driver"
